### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by cindro** [jkulubya/mtn-momo-dotnet#5]
Please make the callbacks optional as intended by MTN's API, this would greatly help with the productivity.

**Comment by jkulubya** [comment]
Hi,
Please try https://www.nuget.org/packages/MtnMomo.NET/1.0.0-alpha-28 and let me know if that's good.

**Comment by cindro** [comment]
I have only tested collections.RequestToPay and the new library still doesn't work.

**Comment by jkulubya** [comment]
Hi,
I've rigged up a quick example here.
https://github.com/jkulubya/momotest

You can get credentials using the info here:
https://github.com/sparkplug/momoapi-node#sandbox-credentials

**Comment by cindro** [comment]
I upgraded to 1.0.0-alpha-37 just now and made a tiny change in my code and everything works now, at least RequestToPay which I tested does.

Thank you for this beautiful library.

**Comment by jkulubya** [comment]
Alright...that’s great to hear. Thanks.
